In [ ]:
#Building a movie recommendation engine using python

In [ ]:
#Import the libraries
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#Load the data
from google.colab import files
uploaded=files.upload()

Saving movie_sample_dataset.csv to movie_sample_dataset.csv


In [ ]:
#Store the data
df=pd.read_csv('movie_sample_dataset.csv')
#Show the first 3 rows of data
df.head(3)

color  ... movie_facebook_likes
0   Color  ...               138000
1   Color  ...                95000
2  color   ...               114000

[3 rows x 13 columns]

In [ ]:
#Get a count of the number of rows/movies in the data set and the number of columns
df.shape

(99, 13)

In [ ]:
#Create a list of important columns  for the recommendation engine
columns=['director_name','actors','genres','movie_title']

In [ ]:
#Adding new column movie_id to dataset
df['Movie_ID'] = range(0, 0+len(df))


In [ ]:
#Show the data
df[columns].head(3)

director_name  ...              movie_title
0    Martin Scorsese  ...  The Wolf of Wall Street
1        Shane Black  ...               Iron Man 3
2  Quentin Tarantino  ...        The Hateful Eight

[3 rows x 4 columns]

In [ ]:
#Check for any missing values in the important columns
a=df[columns].isnull().values.any()
print(a)
df[columns].isnull().sum()

True


director_name    11
actors            0
genres            1
movie_title       0
dtype: int64

In [ ]:
#Cleaning the data containing null values
DataDummies = pd.get_dummies(columns)
DataDummies

actors  director_name  genres  movie_title
0       0              1       0            0
1       1              0       0            0
2       0              0       1            0
3       0              0       0            1

In [ ]:
#Checking the cleaning is successful or not
print(DataDummies.isnull().sum())
b=DataDummies.isnull().values.any()
print(b)

actors           0
director_name    0
genres           0
movie_title      0
dtype: int64
False


In [ ]:
#Create a function to combine the values of the important columns into a single string
def get_important_features(data):
  important_features=[]
  for i in range(0,data.shape[0]):
    important_features.append(str(data['actors'][i]) +' '+ str(data['director_name'][i]) +' '+ str(data['genres'][i]) +' '+str(data['movie_title'][i]))

  return important_features


In [ ]:
#Create a column to hold combined strings
df['important_features'] = get_important_features(df)

#Show the data
df.head(20)

color  ...                                 important_features
0    Color  ...  Leonardo DiCaprio,Matthew McConaughey,Jon Favr...
1    Color  ...  Robert Downey Jr.,Jon Favreau,Don Cheadle Shan...
2   color   ...  Craig Stark,Jennifer Jason Leigh,Zoë Bell Quen...
3    Color  ...  Matt Damon,Kieran Culkin,John Gallagher Jr. Ke...
4    Color  ...  Aidan Turner,Adam Brown,James Nesbitt Peter Ja...
5      NaN  ...  Henry Cavill,Lauren Cohan,Alan D. Purwin nan A...
6    Color  ...  Aidan Turner,Adam Brown,James Nesbitt Peter Ja...
7    Color  ...  Rufus Sewell,Hayley Atwell,Charlotte Rampling ...
8    Color  ...  Chris Hemsworth,Robert Downey Jr.,Scarlett Joh...
9    Color  ...  Chris Hemsworth,Robert Downey Jr.,Scarlett Joh...
10     NaN  ...  Tom Hanks,Jim Sturgess,Jim Broadbent Tom Tykwe...
11   Color  ...  Robin Wright,Goran Visnjic,Joely Richardson Nu...
12   Color  ...  Roma Downey,Amber Rose Revah,Darwin Shaw Chris...
13   Color  ...  Matthew McConaughey,Anne Hathaway,Mackenzie Fo...
14   Color  ...  Aldis Hodge,Neil Brown Jr.,R. Marcos Taylor F....
15     NaN  ...  Ellar Coltrane,Lorelei Linklater,Libby Villari...
16   Color  ...  Leonardo DiCaprio,Christoph Waltz,Ato Essandoh...
17   Color  ...  Bingbing Li,Sophia Myles,Kelsey Grammer Michae...
18     NaN  ...  Tom Hardy,Christian Bale,Joseph Gordon-Levitt ...
19   Color  ...  Aidan Turner,Adam Brown,James Nesbitt Peter Ja...

[20 rows x 15 columns]

In [ ]:
#Convert the text to a matrix of token counts
cm= CountVectorizer().fit_transform(df['important_features'])

In [ ]:
#Get the cosine similarity matrix from the count matrix
cs=cosine_similarity(cm)
#Print the cosine similarity matrix
print(cs)

[[1.         0.12524486 0.17647059 ... 0.13453456 0.070014   0.12964074]
 [0.12524486 1.         0.         ... 0.         0.0745356  0.        ]
 [0.17647059 0.         1.         ... 0.13453456 0.070014   0.06482037]
 ...
 [0.13453456 0.         0.13453456 ... 1.         0.08006408 0.14824986]
 [0.070014   0.0745356  0.070014   ... 0.08006408 1.         0.07715167]
 [0.12964074 0.         0.06482037 ... 0.14824986 0.07715167 1.        ]]


In [ ]:
#Get the shape of the cosine similarity matrix
cs.shape

(99, 99)

In [ ]:
#Get the title of the movie that the user likes
title=input(print('Enter movie name:'))

#Find the movies id
movie_id=df[df.movie_title==title]['Movie_ID'].values[0]

Enter movie name:
The Avengers


In [ ]:
#Create a list of enumerations for the similarity scores
#We get a list of tuples as[(movie_id,similarity score),(...)]
scores= list(enumerate(cs[movie_id]))

In [ ]:
#Sort the list
#Here, x corresponds to scores and position 1 is the similarity score, Reverse=True sorts list in descending order
sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
sorted_scores= sorted_scores[1:]

In [ ]:
#Print the sorted scores
print(sorted_scores)

[(9, 0.9999999999999998), (60, 0.8767140075192089), (41, 0.6454972243679026), (88, 0.5009794328681195), (1, 0.46666666666666656), (66, 0.33333333333333326), (80, 0.33333333333333326), (58, 0.32274861218395134), (25, 0.3131121455425747), (29, 0.28644594961577313), (49, 0.2760262237369417), (28, 0.2666666666666666), (38, 0.2666666666666666), (59, 0.2666666666666666), (5, 0.2581988897471611), (17, 0.2581988897471611), (51, 0.2581988897471611), (84, 0.2581988897471611), (36, 0.2369395511036369), (37, 0.23094010767585027), (44, 0.23094010767585027), (71, 0.223606797749979), (13, 0.21483446221182984), (19, 0.21081851067789195), (34, 0.20701966780270625), (93, 0.20701966780270625), (4, 0.18257418583505536), (89, 0.18257418583505536), (40, 0.14907119849998599), (52, 0.14907119849998599), (53, 0.14907119849998599), (77, 0.14907119849998599), (24, 0.14322297480788657), (83, 0.14322297480788657), (6, 0.1333333333333333), (18, 0.1333333333333333), (30, 0.1333333333333333), (31, 0.1333333333333333)

In [ ]:
#Create a loop to print the first 7 similar movies
j=0
print("The 7 most recommended movies to", title,'are:\n')
for item in sorted_scores:
  movie_title=df[df.Movie_ID==item[0]]['movie_title'].values[0]
  print(j+1, movie_title)
  j=j+1
  if j>7:
    break

The 7 most recommended movies to The Avengers are:

1 The Avengers
2 Avengers: Age of Ultron
3 Captain America: Civil War
4 Captain America: The Winter Soldier
5 Iron Man 3
6 The Judge
7 The Wolverine
8 The Amazing Spider-Man 2
